import type { OAuthProtectedResourceMetadata } from "@modelcontextprotocol/sdk/shared/auth.js";

import {
  SUPPORTED_SCOPES,
  isMcpOAuthEnabled,
  issuer,
  mcpResource,
} from "@/lib/mcp-auth/config";

/**
 * A compatibility alias for the RFC 9728 document served at
 * `/.well-known/oauth-protected-resource/api/mcp`.
 *
 * ## Why this duplicate exists
 *
 * The spec-correct location is the path-suffixed one: the resource is
 * `<origin>/api/mcp`, so its metadata belongs at
 * `/.well-known/oauth-protected-resource/api/mcp`, and that is what the
 * `WWW-Authenticate` header on a 401 points at. A client that follows the header —
 * which the MCP specification requires — finds it there and never reads this file.
 *
 * Not every client follows the header. Some skip the challenge and probe the
 * bare well-known path directly, get a 404, and report the server as not
 * supporting OAuth at all — which is indistinguishable, from the user's side,
 * from the endpoint being broken. That failure is expensive to diagnose and
 * costs nothing to prevent.
 *
 * Serving the identical document here is safe because the document is
 * self-describing: its `resource` field names `<origin>/api/mcp` explicitly, so a
 * client cannot come away believing the protected resource is the site root. The
 * body is generated by the same `config.ts` accessors as the canonical route,
 * so the two cannot drift.
 *
 * This is a shim for client behaviour, not a second resource. If a second MCP
 * resource is ever added to this deployment, delete this file — at that point a
 * bare path genuinely would be ambiguous about which resource it describes, and
 * answering it with a guess would be worse than answering 404.
 */

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(): Promise<Response> {
  if (!isMcpOAuthEnabled()) {
    return new Response("Not Found", { status: 404 });
  }

  try {
    const metadata: OAuthProtectedResourceMetadata = {
      resource: mcpResource(),
      authorization_servers: [issuer()],
      scopes_supported: [...SUPPORTED_SCOPES],
      bearer_methods_supported: ["header"],
      resource_name: "ESE blog drafting (MCP)",
    };

    return Response.json(metadata, {
      headers: { "cache-control": "public, max-age=3600" },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("[mcp-oauth] protected resource metadata unavailable (root alias)", { message });
    return Response.json(
      { error: "server_error", error_description: message },
      { status: 500, headers: { "cache-control": "no-store" } },
    );
  }
}
